import type { Metadata } from "next";
import { Provider } from "../components/ui/provider";
import { Container } from "@chakra-ui/react";
import { Arimo } from "next/font/google";
import Header from "../components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const arimo = Arimo({ subsets: ["latin"], weight: ["400", "700"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html suppressHydrationWarning className={arimo.className}>
      <body>
        <Provider>
          <Container maxWidth={"100%"} background={"bg"} px="0">
            <Header />
            {children}
          </Container>
        </Provider>
      </body>
    </html>
  );
}
